// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpwQLznYCtk3OqZY05i6Z2VmYPD-5oni4',
    appId: '1:979454246456:android:dfaee2c4fe92fc2a74f0cd',
    messagingSenderId: '979454246456',
    projectId: 'clinica-d38d2',
    storageBucket: 'clinica-d38d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdYJggz6HQvAnLgI6a9_jdzYkuAbB5MR4',
    appId: '1:979454246456:ios:fc1ad3b2dfcd871174f0cd',
    messagingSenderId: '979454246456',
    projectId: 'clinica-d38d2',
    storageBucket: 'clinica-d38d2.appspot.com',
    androidClientId:
        '979454246456-ksko6npei9hplalpo1p5977pnsu8c8hu.apps.googleusercontent.com',
    iosClientId:
        '979454246456-4j2asui9svk3c70n59lbfqnpfqn61n90.apps.googleusercontent.com',
    iosBundleId: 'com.example.clinigramApp',
  );

  static const FirebaseOptions clinigrWeb = FirebaseOptions(
      apiKey: "AIzaSyCOT-AQYSwPZ9VawHCByZ3k7WDX_AIfYZo",
      authDomain: "clinica-d38d2.firebaseapp.com",
      projectId: "clinica-d38d2",
      storageBucket: "clinica-d38d2.appspot.com",
      messagingSenderId: "979454246456",
      appId: "1:979454246456:web:c975ee12e9e4abeb74f0cd",
      measurementId: "G-4NX6VGZPKL");

  static const FirebaseOptions clinicateWeb = FirebaseOptions(
      apiKey: "AIzaSyDpwQLznYCtk3OqZY05i6Z2VmYPD-5oni4",
      authDomain: "clinica-d38d2.firebaseapp.com",
      projectId: "clinica-d38d2",
      storageBucket: "clinica-d38d2.appspot.com",
      messagingSenderId: "979454246456",
      appId: "1:979454246456:web:76fbd85132d8de0374f0cd",
      measurementId: "G-VZGG12ZZ38");

  static const FirebaseOptions web = clinigrWeb;
}
